name: electron-drag-click

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install Xcode Command Line Tools
      run: |
        xcode-select --install || true

    - name: Install setuptools
      run: python3 -m pip install setuptools

    - name: Install dependencies
      run: npm ci

    - name: Verify native module build
      run: npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: native-module-20.x
        path: |
          build/
          *.node
        retention-days: 7
